### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by drakkar1969** [arc-design/arc-theme#245]
Would it be possible to have a new release, there have been quite a few commits since the last release

Thanks!

**Comment by bjo81** [comment]
A new release including #218 would be nice!

**Comment by akoyaxd** [comment]
It's been quite some time.. 
We'll probable see a new release with Gnome 3.24, at least I hope so.

**Comment by fossfreedom** [comment]
@drakkar1969 and everyone - apologies for the delays.

Ok - new organisation and lets reinvigorate the project.  @drakkar1969 hopefully you will accept the invitation to join.

**Comment by akoyaxd** [comment]
No need to apology! :D
Thank you for your work! :)
