### ISSUE TITLE
Extra margin on stack switcher after restyle pathbar commit

### ISSUE THREAD

**Issue by ariflukito** [arc-design/arc-theme#251]
Hi,

It looks like the stack switcher is broken after this commit a6cf4045f6f59fae91831401f9b3bbcfd72d0916.
There's an extra margin between the tabs and the tab jumps when you hover on it.

You can see it on the screenshot below. The top one with the commit reverted and the bottom one with the original commit.
![stackswitcher](https://user-images.githubusercontent.com/5508660/58617291-17dcd600-8303-11e9-8a4f-bbf8307c25de.png)

- Distribution (with version): Arch Linux
- Desktop environment (with version): GNOME 3.32.2
- Arc version/commit (don't put "latest"): 2c45d9e
- GTK+ 3 version: 1:3.24.8-1
- Murrine engine version: 0.98.2-3
- `gnome-themes-extras` version: 3.28-1
- Installation method (package or source): Source

**Comment by fossfreedom** [comment]
thx.  What app is that?

**Comment by ariflukito** [comment]
That's GNOME Clocks. Happens on any app that uses stack switcher like GNOME Calendar.

**Comment by jnsh** [comment]
I fail to understand how https://github.com/NicoHood/arc-theme/commit/a6cf4045f6f59fae91831401f9b3bbcfd72d0916 would cause this, but the issue is not present on my fork, and I think this commit should fix it: https://github.com/jnsh/arc-theme/commit/26078d3626813ac84f2310131e430020fdd3d622

**Comment by ariflukito** [comment]
I can confirm jnsh/arc-theme@26078d3 fixes the problem. Thank you @jnsh.
