### ISSUE TITLE
Clock/Date color

### ISSUE THREAD

**Issue by rmassidda** [arc-design/arc-theme#254]
![arc](https://user-images.githubusercontent.com/24830255/59056497-a10e8280-8898-11e9-9ff9-bd3a7471ac42.png)

The color of the string in the top bar is light blue instead of white.

## Details

- Fedora 30
- Gnome 3.32.2
- Package 20181022-2.fc30
- GTK+ 3 version: 3.24.8

**Comment by drakkar1969** [comment]
Fixed in https://github.com/NicoHood/arc-theme/commit/14798358e1614dc1bb7318b301a6bad8b20a45f3 and then https://github.com/NicoHood/arc-theme/commit/37762db8f85b46c54f846a2b4f1e062023df433c

**Comment by brainbug89** [comment]
I had to switch to https://launchpad.net/~fossfreedom/+archive/ubuntu/arc-gtk-theme-daily to have the fixed version.
