### ISSUE TITLE
GtkInfoBar doesn't respect message type

### ISSUE THREAD

**Issue by shelacek** [arc-design/arc-theme#259]
Hello,
all infobar types have same background color (`$selected_bg_color`):
https://github.com/NicoHood/arc-theme/blob/2c45d9e4b4a120201dc029a10937058a2e9e094b/common/gtk-3.0/3.20/sass/_common.scss#L2826-L2833

![infobar-colors](https://user-images.githubusercontent.com/12158214/62458762-076f2e80-b77e-11e9-9978-f132717d7c02.png)

Is there any reason for this? Can't we use colors like `$warning_color` and `$error_color`?

### Details

- Distribution (with version): Fedora 29 (Workstation Edition)
- Desktop environment (with version): GNOME Shell 3.30.2
- Arc version/commit (don't put "latest"): [20190330](https://github.com/NicoHood/arc-theme/releases/tag/20190330)
- GTK+ 3 version: 3.24.1-2.fc29.x86_64
  - Murrine engine version: 0.98.2-15.fc29.x86_64
  - `gnome-themes-extras` version: 3.28-2.fc29.x86_64
- Installation method (package or source): source

**Comment by fossfreedom** [comment]
reasonable request.


change would be something like the following:

```
infobar {
  border-style: none;
  &.info { background-color: $success_color; }
  &.question { background-color: $suggested_color; }
  &.warning { background-color: $warning_color; }
  &.error { background-color: $error_color; }
  &.info,
  &.question,
  &.warning,
  &.error {
    color: $selected_fg_color;
    caret-color: currentColor;
    button { @extend %selected-button }
    selection {
      color: $selected_bg_color;
      background-color: $selected_fg_color;
    }
    *:link { @extend %link_selected; }
  }
}
```
