### ISSUE TITLE
XFCE 4.14 Arc-darker taskbar changed 

### ISSUE THREAD

**Issue by MajuTo** [arc-design/arc-theme#266]
Hi,
i'm using Manjro 18.0.4 with XFCE 4.14.0-1 and arc-gtk-theme 20190330-1

Since we have XFCE4.14, arc-darker taskbar is pretty ugly.
With previous version, it looked like arc-dark, but now there many "light" items.

Arc-dark
![arc-dark](https://user-images.githubusercontent.com/6802426/64114275-e0ac1400-cd8c-11e9-945e-aa882b5b9fc8.png)

Arc-darker
![arc-darker](https://user-images.githubusercontent.com/6802426/64114289-e9044f00-cd8c-11e9-8f97-143ed2fd0a9d.png)

Is there any way to have it like it was before ?

Thanks

**Comment by fossfreedom** [comment]
https://github.com/arc-design/arc-theme/pull/268
