### ISSUE TITLE
Black background on All Applications icon in Dash

### ISSUE THREAD

**Issue by Aerozolic** [arc-design/arc-theme#278]
- Distribution (with version): Pop!_OS 19.10
  - Base distribution (if have, with version):
- Desktop environment (with version): Gnome
- Arc version/commit (don't put "latest"): 20190917
- GTK+ 3 version: 3.24.12
  - Murrine engine version: 0.98.2
  - `gnome-themes-extras` version: 3.28
- Installation method (package or source): package

The background of All Applications icon is black. This is not happening with other shell themes.

       
![Screenshot from 2019-12-15 16-53-00](https://user-images.githubusercontent.com/25500346/70864686-506d9580-1f5d-11ea-9733-b059f21e317e.png)

**Comment by nguyenkien** [comment]
This is by design

**Comment by Aerozolic** [comment]
> This is by design

Odd design then. If I change the default all applications icon then it still shows the black background. It looks pretty ugly if the custom icon is round for example.

**Comment by nguyenkien** [comment]
Yes, it look really ugly. 
However you can remove it, open file `gnome-shell/gnome-shell.css` search for `.show-apps .overview-icon`, and remove `background-color: rgba(0, 0, 0, 0.5);` and save it

**Comment by Aerozolic** [comment]
> Yes, it look really ugly.
> However you can remove it, open file `gnome-shell/gnome-shell.css` search for `.show-apps .overview-icon`, and remove `background-color: rgba(0, 0, 0, 0.5);` and save it

I was able to remove the static background but hovering over and activate state backgrounds are still messed up/look different compared to other icons on the dash.

PS. Sorry for off topic.

**Comment by nguyenkien** [comment]
Repeat for .show-apps:active or :hover ...

**Comment by Aerozolic** [comment]
> Repeat for .show-apps:active or :hover ...

Yeah, I found those but struggle with the options: color codes etc to set them up right.
Thanks anyway!
